using System;

public enum PlayerFields
{
	DuelArbiter = 212,
	WowAccount = 216,
	LootTargetGUID = 220,
	PlayerFlags = 224,
	PlayerFlagsEx,
	GuildRankID,
	GuildDeleteDate,
	GuildLevel,
	HairColorID,
	CustomDisplayOption,
	Inebriation,
	ArenaFaction,
	DuelTeam,
	GuildTimeStamp,
	QuestLog,
	VisibleItems = 1035,
	PlayerTitle = 1073,
	FakeInebriation,
	VirtualPlayerRealm,
	CurrentSpecID,
	TaxiMountAnimKitID,
	AvgItemLevel,
	CurrentBattlePetBreedQuality = 1082,
	Prestige,
	HonorLevel,
	InvSlots,
	FarsightObject = 1833,
	SummonedBattlePetGUID = 1837,
	KnownTitles = 1841,
	Coinage = 1853,
	XP = 1855,
	NextLevelXP,
	Skill,
	CharacterPoints = 2305,
	MaxTalentTiers,
	TrackCreatureMask,
	TrackResourceMask,
	MainhandExpertise,
	OffhandExpertise,
	RangedExpertise,
	CombatRatingExpertise,
	BlockPercentage,
	DodgePercentage,
	DodgePercentageFromAttribute,
	ParryPercentage,
	ParryPercentageFromAttribute,
	CritPercentage,
	RangedCritPercentage,
	OffhandCritPercentage,
	SpellCritPercentage,
	ShieldBlock,
	ShieldBlockCritPercentage,
	Mastery,
	Speed,
	Lifesteal,
	Avoidance,
	Sturdiness,
	Versatility,
	VersatilityBonus,
	PvpPowerDamage,
	PvpPowerHealing,
	ExploredZones,
	RestInfo = 2653,
	ModDamageDonePos = 2657,
	ModDamageDoneNeg = 2664,
	ModDamageDonePercent = 2671,
	ModHealingDonePos = 2678,
	ModHealingPercent,
	ModHealingDonePercent,
	ModPeriodicHealingDonePercent,
	WeaponDmgMultipliers,
	WeaponAtkSpeedMultipliers = 2685,
	ModSpellPowerPercent = 2688,
	ModResiliencePercent,
	OverrideSpellPowerByAPPercent,
	OverrideAPBySpellPowerPercent,
	ModTargetResistance,
	ModTargetPhysicalResistance,
	LocalFlags,
	NumRespecs,
	SelfResSpell,
	PvpMedals,
	BuybackPrice,
	BuybackTimestamp = 2710,
	YesterdayHonorableKills = 2722,
	LifetimeHonorableKills,
	WatchedFactionIndex,
	CombatRatings,
	PvpInfo = 2757,
	MaxLevel = 2799,
	ScalingPlayerLevelDelta,
	MaxCreatureScalingLevel,
	NoReagentCostMask,
	PetSpellPower = 2806,
	Researching,
	ProfessionSkillLine = 2817,
	UiHitModifier = 2819,
	UiSpellHitModifier,
	HomeRealmTimeOffset,
	ModPetHaste,
	AuraVision,
	OverrideSpellsID,
	LfgBonusFactionID,
	LootSpecID,
	OverrideZonePVPType,
	BagSlotFlags,
	BankBagSlotFlags = 2832,
	InsertItemsLeftToRight = 2839,
	QuestCompleted,
	Honor = 4590,
	HonorNextLevel,
	End
}
