using System;

public enum UnitFields
{
	Charm = 12,
	Summon = 16,
	Critter = 20,
	CharmedBy = 24,
	SummonedBy = 28,
	CreatedBy = 32,
	DemonCreator = 36,
	Target = 40,
	BattlePetCompanionGUID = 44,
	BattlePetDBID = 48,
	ChannelData = 50,
	SummonedByHomeRealm = 52,
	Sex,
	DisplayPower,
	OverrideDisplayPowerID,
	Health,
	Power = 58,
	MaxHealth = 64,
	MaxPower = 66,
	PowerRegenFlatModifier = 72,
	PowerRegenInterruptedFlatModifier = 78,
	Level = 84,
	EffectiveLevel,
	ScalingLevelMin,
	ScalingLevelMax,
	ScalingLevelDelta,
	FactionTemplate,
	VirtualItems,
	Flags = 96,
	Flags2,
	Flags3,
	AuraState,
	AttackRoundBaseTime,
	RangedAttackRoundBaseTime = 102,
	BoundingRadius,
	CombatReach,
	DisplayID,
	NativeDisplayID,
	MountDisplayID,
	MinDamage,
	MaxDamage,
	MinOffHandDamage,
	MaxOffHandDamage,
	AnimTier,
	PetNumber,
	PetNameTimestamp,
	PetExperience,
	PetNextLevelExperience,
	ModCastingSpeed,
	ModSpellHaste,
	ModHaste,
	ModRangedHaste,
	ModHasteRegen,
	ModTimeRate,
	CreatedBySpell,
	NpcFlags,
	EmoteState = 126,
	Stats,
	StatPosBuff = 131,
	StatNegBuff = 135,
	Resistances = 139,
	ResistanceBuffModsPositive = 146,
	ResistanceBuffModsNegative = 153,
	ModBonusArmor = 160,
	BaseMana,
	BaseHealth,
	ShapeshiftForm,
	AttackPower,
	AttackPowerModPos,
	AttackPowerModNeg,
	AttackPowerMultiplier,
	RangedAttackPower,
	RangedAttackPowerModPos,
	RangedAttackPowerModNeg,
	RangedAttackPowerMultiplier,
	SetAttackSpeedAura,
	MinRangedDamage,
	MaxRangedDamage,
	PowerCostModifier,
	PowerCostMultiplier = 182,
	MaxHealthModifier = 189,
	HoverHeight,
	MinItemLevelCutoff,
	MinItemLevel,
	MaxItemLevel,
	WildBattlePetLevel,
	BattlePetCompanionNameTimestamp,
	InteractSpellID,
	StateSpellVisualID,
	StateAnimID,
	StateAnimKitID,
	StateWorldEffectID,
	ScaleDuration = 204,
	LooksLikeMountID,
	LooksLikeCreatureID,
	LookAtControllerID,
	LookAtControllerTarget,
	End = 212
}
